name: triggerflow
 
on:
  push:  
    branches-ignore:
      - "main"
jobs:
  trigger:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test this
        run: echo hello world